### ISSUE TITLE
Yandex server

### ISSUE THREAD

**Issue by mdikcinar** [Xinor/kitapbar.com#1]
What exactly we should do to run this project? i have tried change yandex cloud jwt key in .env file but it still gets nothing while searching. Am i doing it wrong or should i do more to set it up.
I think i got it, there must be added yandex folders to scan.

**Comment by Xinor** [comment]
this repo can't give any yandex disk link because it doesn't have a copyright notice. however, website links can be added where yandex disk links can be found.

- [x] add web pages where yandex disk links are shared

**Comment by Xinor** [comment]
6d7b782054dc861eb3056994023a8c2e5e0a9152
